name: yet-another-sub-web

services:
  yet-another-sub-web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      TZ: America/New_York
      NEXT_PUBLIC_BACKENDS: http://127.0.0.1:25500/sub?
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - network

networks:
  network:
